### ISSUE TITLE
[Vol2brain] MNI normalization not perfect

### ISSUE THREAD

**Issue by IFaillenot** [volBrain/platform#1]
Thank you for this beautiful platform !

I used the Vol2brain pipeline. 
For a patient with a lesion and atrophy, the MNI transformation was not perfect and I wonder if there is some consequence on the results (surprisingly, the results seem perfect)

in the screenshot : 
in grey : the normalized T1 after fmriprep
in redyel : the normalized T1 after vol2brain. 
This is particularly different for the ventricules and on the top of the brain. 
<img width="891" alt="Capture d’écran 2023-12-07 à 16 00 11" src="https://github.com/volBrain/platform/assets/66122581/4f5b217e-16c9-4c53-86d9-0cc98a01f0e9">

It would be nice to have a quality check of the normalization processing especially if the results depend on it (maybe a superimposition of the MNI template and the mni_t1 images?)
My concern is that I need to segment lesion with different tools, all working in MNI152 space

 - mac OS : 14.1
 - Browser safari 17.1

**Comment by pierrickvolbrain** [comment]
The segmentation results depend very slightly on the quality of the affine registration. The only critical issue is a total failure of the registration. If you want a tool with quality control of the registration, use AssemblyNet pipeline.

If your concern is that you need to segment lesion with different tools, all working in MNI152 space, this is not related to the quality of the affine registration. You want to project all your results in the native space using the the same transformation to MNI space.  

So, first you have to take one of the registration affine matrix from your tools tools as a reference (take the affine matrix from your favorite tool). Then, use the corresponding affine matrix to interpolated all the another results **in the native** into the same MNI space thanks to this matrix.

**Comment by jmanjon** [comment]
I would sugest to use itksnap viewer.

some viewers does not read headers properly

**Comment by jmanjon** [comment]
Also be sure you are opening the same case . This seems not the case.

**Comment by IFaillenot** [comment]
> Also be sure you are opening the same case . This seems not the case.

it is !  look at the lesion: 2 persons don't have the same lesion. 
on the right : his t1 after fmriprep normalization on MNI152
on the left: the vol2brain MNI image (which do not look like the MNI152 template)

![Capture d’écran 2023-12-08 à 15 32 40](https://github.com/volBrain/platform/assets/66122581/90ca3381-cb1a-4794-ae9e-e3c259efadf3)

**Comment by pierrickvolbrain** [comment]
I guess that you used nonlinear registration in fmriprep (see their doc) while we are using affine transformation. This is normal that non linear registration produces an image more similar to the MNI Atlas than affine transformation.

https://fmriprep.org/en/stable/workflows.html
"Finally, spatial normalization to standard spaces is performed using ANTs’ antsRegistration in a multiscale, mutual-information based, nonlinear registration scheme"

**Comment by IFaillenot** [comment]
Haaaa sorry ! I did not see that you used affine transformation only....
so I need to work on the native image.... and my other post is more important then...

thank you both for your quick answers
