### ISSUE TITLE
[BUG] Can't run HIPS monospectral without specifying second (T2w) image

### ISSUE THREAD

**Issue by sarenseeley** [volBrain/platform#5]
As of today, the HIPS pipeline interface is requiring a second image in order for the "Upload" button to appear even when "monospectral" is selected.

<img width="1107" alt="Screen Shot 2024-04-15 at 10 03 53 AM" src="https://github.com/volBrain/platform/assets/31291534/df94bcbf-f929-484f-b061-64a3f850bb8f">

This happens on both Safari & Chrome.

**Comment by sarenseeley** [comment]
I tried to see if it would work to put in a second unrelated file (since monomodal should only use the T1w image as input) but the job does not run; it says it has run successfully but the job is empty of outputs and only contains the README.pdf and the yaml file).

<img width="1097" alt="Screen Shot 2024-04-15 at 11 57 21 AM"  src="https://github.com/volBrain/platform/assets/31291534/f30b2a64-eeda-4ce2-8dd1-21d15ae618d8">

[sub-092_T1w_job1678650_archive.zip](https://github.com/volBrain/platform/files/14981499/sub-092_T1w_job1678650_archive.zip)

**Comment by pierrickvolbrain** [comment]
this has been fixed. Thanks for the message (and to close this issue)

**Comment by sarenseeley** [comment]
Wonderful, thank you so much! Confirmed that's working now.
